server:
  port: 9000
  tomcat:
    max-connections: 10000
    accept-count: 1000
    threads:
      max: 3000
      min-spare: 1000
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fastsns?userSSL=false&useUnicode=true&PublicKeyRetrieval=true
    username: root
    password: root1234!!
  data:
    host: localhost
    port: 6379