server:
  port: 9010
spring:
  data:
    redis:
      host: localhost
      port: 6379
schedule:
  enable: true
---
spring:
  config:
    activate:
      on-profile: test
  data:
    redis:
      host: localhost
      port: 63790
schedule:
  enable: false