spring:

  batch:
    jdbc:
      initialize-schema: always
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/spring_batch
    url: jdbc:mysql://localhost:3306/spring_batch?userSSL=false&useUnicode=true&PublicKeyRetrieval=true
    username: root
    password: root1234!!
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl