server:
  port: 9010
spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3306/fastsns?userSSL=false&useUnicode=true&PublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: root
    password: root1234!!
  data:
    redis:
      host: localhost
      port: 6379
